[package]
name = "opensk-wasefire"
version = "0.1.0"
authors = [
  "Fabian Kaczmarczyck <kaczmarczyck@google.com>",
  "Guillaume Endignoux <guillaumee@google.com>",
  "Jean-Michel Picod <jmichel@google.com>",
  "Julien Cretin <cretin@google.com>",
]
license = "Apache-2.0"
edition = "2024"

[dependencies]
portable-atomic-util = { version = "0.2.6", default-features = false, features = ["alloc"] }
wasefire-common = { version = "0.1.0", optional = true }

[dependencies.wasefire]
version = "0.8.1"
default-features = false
features = [
  "api-button",
  "api-clock",
  "api-crypto-cbc",
  "api-crypto-ecdh",
  "api-crypto-ecdsa",
  "api-crypto-hash",
  "api-crypto-hkdf",
  "api-led",
  "api-rng",
  "api-store",
  "api-timer",
  "api-usb-ctap",
]

[dependencies.opensk]
path = "libraries/opensk"
default-features = false

[features]
default = ["config-command", "ctap1"]
config-command = ["opensk/config_command"]
ctap1 = ["opensk/with_ctap1"]
debug = ["opensk/debug_ctap"]
ed25519 = ["opensk/ed25519", "wasefire/api-crypto-ed25519"]
fingerprint = ["dep:wasefire-common", "opensk/fingerprint", "wasefire/api-fingerprint-matcher"]
led-1 = []
test = ["opensk/std", "wasefire/test"]

[build-dependencies]
uuid = { version = "0.8", features = ["v4"] }

[lints]
rust.dead_code = "allow"
