[toolchain]
channel = "nightly-2026-04-01"
components = ["clippy", "miri", "rustfmt", "rust-src"]
targets = [
    "thumbv7em-none-eabi",
    "wasm32-unknown-unknown",
    "riscv32imac-unknown-none-elf",
    "riscv32imc-unknown-none-elf",
]
