[toolchain]
channel = "nightly-2023-11-01"
components = ["clippy", "miri", "rustfmt"]
targets = ["thumbv7em-none-eabi",
           "riscv32imac-unknown-none-elf",
           "riscv32imc-unknown-none-elf"]
