[package]
name = "heapviz"
version = "0.1.0"
authors = [
  "Guillaume Endignoux <guillaumee@google.com>",
]
license = "Apache-2.0"
edition = "2018"

[dependencies]
clap = "~2.27.*"
lazy_static = "1.4.0"
ncurses = "5.99.0"
regex = "1"
