---
name: Build supported boards
on:
  push:
    paths:
     - 'patches/tock/*'
     - 'third_party/tock/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_boards:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: Install Rust toolchain
        run: rustup show
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Set up OpenSK
        run: ./setup.sh

      - name: Building board nrf52840dk_opensk
        run: ./deploy.py --board=nrf52840dk_opensk --no-app --programmer=none
      - name: Building board nrf52840_dongle_opensk
        run: ./deploy.py --board=nrf52840_dongle_opensk --no-app --programmer=none
      - name: Building board nrf52840_dongle_dfu
        run: ./deploy.py --board=nrf52840_dongle_dfu --no-app --programmer=none
      - name: Building board nrf52840_mdk_dfu
        run: ./deploy.py --board=nrf52840_mdk_dfu --no-app --programmer=none
