name: Binary size report
on: pull_request

jobs:
  cargo_bloat:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # Setup
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-bloat

      # First run: PR
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up OpenSK
        run: ./setup.sh
      - name: Run bloat on the PR
        working-directory: ./third_party/wasefire
        run: cargo xtask --release --native applet rust ../.. --opt-level=z --features=ctap1,config-command runner nordic --opt-level=z --features=usb-ctap --features=software-crypto-aes256-cbc,software-crypto-hmac-sha256 --features=software-crypto-p256-ecdh,software-crypto-p256-ecdsa --measure-bloat >> "$GITHUB_WORKSPACE/.github/workflows/bloat_output_new.txt"

      # Second run: HEAD
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.base_ref }}
          path: OpenSK_base
      - name: Set up OpenSK
        working-directory: ./OpenSK_base
        run: ./setup.sh
      - name: Run bloat on base
        working-directory: ./OpenSK_base/third_party/wasefire
        run: cargo xtask --release --native applet rust ../.. --opt-level=z --features=ctap1,config-command runner nordic --opt-level=z --features=usb-ctap --features=software-crypto-aes256-cbc,software-crypto-hmac-sha256 --features=software-crypto-p256-ecdh,software-crypto-p256-ecdsa --measure-bloat >> "$GITHUB_WORKSPACE/.github/workflows/bloat_output_old.txt"

      - name: Run output formatter to echo workflow command
        run: .github/workflows/bloat_formatter.sh bloat_output_new.txt bloat_output_old.txt bloat_comment.md

      - name: Add summary
        run: cat .github/workflows/bloat_comment.md >> $GITHUB_STEP_SUMMARY
