---
name: CBOR tests
on:
  push:
    paths:
      - 'libraries/cbor/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cbor_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: Install Rust toolchain
        run: rustup show
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Set up OpenSK
        run: ./setup.sh

      - name: Unit testing of CBOR library (release mode)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path libraries/cbor/Cargo.toml --release

      - name: Unit testing of CBOR library (debug mode)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path libraries/cbor/Cargo.toml
