name: Continuous Integration

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  schedule:
    - cron: 30 1 * * 2 # every Tuesday at 1:30 UTC

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  runtests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - run: ./setup.sh
      - run: rustup component add rustfmt --toolchain nightly
      - run: rustup component add clippy --toolchain nightly
      - run: rustup component add audit --toolchain nightly
      - run: ./run_desktop_tests.sh
