---
name: Crypto library tests
on:
  push:
    paths:
      - 'libraries/crypto/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'libraries/crypto/**'

jobs:
  crypto_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - uses: actions-rs/toolchain@v1
        with:
          target: thumbv7em-none-eabi
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Set up OpenSK
        run: ./setup.sh

      - run: echo "RUSTFLAGS=-C target-feature=+aes" >> $GITHUB_ENV

      - name: Unit testing of crypto library (release mode)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path libraries/crypto/Cargo.toml --release --features std,derive_debug

      - name: Unit testing of crypto library (debug mode)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path libraries/crypto/Cargo.toml --features std,derive_debug
